### ISSUE TITLE
Change background to reflect both Elixir and Elm

### ISSUE THREAD

**Issue by wende** [Baransu/elchemy-page#1]
linear-gradient(to right, #4e2a8e, #60B5CC);

<img width="1407" alt="screen shot 2017-09-25 at 18 55 02" src="https://user-images.githubusercontent.com/4634386/30820738-214da1be-a223-11e7-9a50-3bd44dbacaf3.png">

**Comment by baransu** [comment]
Resolved via: https://github.com/Baransu/elchemy-page/commit/eca62b4eb7bd7b94539f7a3576e9a44f48c170bc
