### ISSUE TITLE
Use Fork me on github ribbon

### ISSUE THREAD

**Issue by wende** [Baransu/elchemy-page#3]
https://github.com/blog/273-github-ribbons

And remove this:
<img width="154" alt="screen shot 2017-09-25 at 19 07 09" src="https://user-images.githubusercontent.com/4634386/30821186-c498b7f4-a224-11e7-86ce-567ca5fe98be.png">

**Comment by baransu** [comment]
Resolved via: https://github.com/Baransu/elchemy-page/commit/eca62b4eb7bd7b94539f7a3576e9a44f48c170bc
