### ISSUE TITLE
Automate building into elchemy repository

### ISSUE THREAD

**Issue by wende** [Baransu/elchemy-page#8]
Make building new version of the compiler and then new version of the website for elchemy repo automated

**Comment by baransu** [comment]
With this PR (https://github.com/wende/elchemy/pull/210) adding `make build-page` into release pipeline should be efficient enough. Waiting for mentioned PR to be merged to close this issue.

**Comment by wende** [comment]
Although it is merged, there are some elements of the build pipeline that won't work without global libraries installed 
<img width="720" alt="screen shot 2017-11-27 at 00 18 52" src="https://user-images.githubusercontent.com/4634386/33245466-92107afa-d308-11e7-9dd6-355616c4b668.png">

**Comment by baransu** [comment]
This is related to local version of the node-sass. There could be problem with version we’re using and the version of node you have on your machine. Node-sass comes with prebuild libraries for every node version so this can be problematic for example if you’re using newest node version and old node-sass.
